version: 2

jobs:
  # build:
  #   working_directory: ~/projetcs/RNCircleCI # directory where steps will run
  #   docker: # run the steps with Docker
  #     - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
  #   steps: # a collection of executable commands
  #     - checkout # special step to check out source code to working directory
  #     - run:
  #         name: install-npm-modules
  #         command: npm install
  ios:
    macos:
      xcode: 11.1.0
      # shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Build and run the ios app
          command:  cd ios && fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: RNCircleCI

      - store-test-results:
          path: test_output/report.xml
      - store-artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      # - android:
      #     requires:
      #       - node
      - ios:
          requires:
            - node
      # - run: npm install

      # - restore_cache: # special step to restore the dependency cache
      #     # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      #     key: dependency-cache-{{ checksum "package-lock.json" }}

      # - save_cache: # special step to save the dependency cache
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules

      # - run:
      #     command: bundle install
      #     working_directory: ios

      # - save_cache:
      #     key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
      #     paths:
      #       - vendor/bundle
